### ISSUE TITLE
Erro ao compilar game.cpp LINUX

### ISSUE THREAD

**Issue by itspaiva** [eclipse606/tfs#1]
Quando tentei compilar o servidor acabou dando esse erro no game.cpp:

game.cpp: In member function ‘uint32_t Game::spawnDivider(MonsterType*)’:
game.cpp:7344:26: error: ‘class MonsterType’ has no member named ‘ignoreSpawnBoost’
 7344 |     if (mType && !mType->ignoreSpawnBoost) {
      |                          ^~~~~~~~~~~~~~~~

Saida inteira do [make](https://pastebin.com/ifgmb8xM)

**Comment by eclipse606** [comment]
@itspaiva fixed! [c88c583](https://github.com/eclipse606/tfs/commit/c88c583)
